version: '3.7'

services:
  caddysvr:
    container_name: cdysvr
    image: rvsprxy:caddysvr # behavior of 'image' changes if 'build' also present
    build:
      context: caddysvr
      target: alpine
      #      target: scratch
      args:
        - CADDY_SOURCE_VERSION
    restart: on-failure:3
    volumes:
      - ./caddysvr/certs/acme:/etc/caddy/acme  # to save acme
      - ./caddysvr/certs/ocsp:/etc/caddy/ocsp  # to save certificates

      - ./CaddyfileStarter.json:/etc/caddy/Caddyfile
    networks:
      - lixirdev_prxynet
    ports:
      # "HOST:CONTAINER"
      - "${CADDY_VISIBLE_PORT}:${CADDY_TRANSFER_PORT}"
    command: ["run", "--config", "/etc/caddy/Caddyfile"]

  ###############################################################################
  genconfig:
    container_name: gncfg
    image: rvsprxy:genconfig # behavior of 'image' changes if 'build' also present
    build:
      context: genconfig
    restart: on-failure:3
    environment:
      - CADDY_TRANSFER_PORT
      - HOST_IP
      - DOCKER_API_VERSION
      - DOCKER_SOCKET
      - NETWORK_NAME
      - VERBOSE_DEBUG
      - CADDY_ADMIN_PORT
    volumes:
      - ${DOCKER_SOCKET}:${DOCKER_SOCKET}:ro     # needs socket to read events
    networks:
      - lixirdev_prxynet
    command: ["tail", "-f"]
    depends_on:
      - caddysvr

  ###############################################################################


networks:
  lixirdev_prxynet:
    driver: bridge
    external: true
