version: '3.7'

services:
  caddysvr:
    container_name: cdysvr
    image: rvsprxy:caddysvr # 'image' becomes 'container label' if 'build' also present
    build:
      context: caddysvr
      target: alpine          # good for local testing and debug
      #      target: scratch  # leanest and most secure option for production
      args:
        - XDG_DATA_HOME
        - CADDY_SOURCE_VERSION
    restart: on-failure:0      # change this to something like 3 in production
    environment:
      - HOST_IP
      - XDG_DATA_HOME
    volumes:
      - ./caddysvr/conf:${XDG_DATA_HOME}
      - ./caddysvr/CaddyfileStarter.json:${XDG_DATA_HOME}/Caddyfile
    networks:
      - lixirdev_prxynet
    ports:
      # "HOST:CONTAINER"
      - "${CADDY_VISIBLE_PORT}:${CADDY_TRANSFER_PORT}"
    command: ["run", "--config", "${XDG_DATA_HOME}/Caddyfile"]

  ###############################################################################
  genconfig:
    container_name: gncfg
    image: rvsprxy:genconfig # 'image' becomes 'container label' if 'build' also present
    build:
      context: genconfig
    restart: on-failure:0    # change this to something like 3 in production
    environment:
      - CADDY_TRANSFER_PORT
      - HOST_IP
      - DOCKER_API_VERSION
      - DOCKER_SOCKET
      - NETWORK_NAME
      - VERBOSE_DEBUG
      - CADDY_ADMIN_PORT
    volumes:
      - ${DOCKER_SOCKET}:${DOCKER_SOCKET}:ro  # using socket option to read docker events
    networks:
      - lixirdev_prxynet
    command: ["tail", "-f"]
    depends_on:
      - caddysvr

  ###############################################################################


networks:
  lixirdev_prxynet:
    driver: bridge
    external: true
