version: '3.7'

services:
  nodebasic:
    container_name: ndbsc
    image: rvsprxy:nodebasic # behavior of 'image' changes if 'build' also present
    build:
      context: .
    restart: on-failure:3
    environment:
      - NODE_SVR_PORT
    volumes:
      - ./src:/src
    networks:
      - lixirdev_prxynet
    command: ["/src/main.js"]
    labels:
      - "virtual.server=nodebasic"  # docker host
      - "virtual.host=karamba.com karamba.com"  # your domains separated with a space
      - "virtual.alias=www.karamba.com"  # alias for your domain (optional) separated with a space
      - "virtual.port=${NODE_SVR_PORT}"  # exposed port of this container
      - "virtual.tls-email=your@tlsworthyemail.com"  # ssl is now on
      - "virtual.websockets" # enable websocket passthrough
      - "virtual.autohttps=false" # enable automatic https


networks:
  lixirdev_prxynet:
    driver: bridge
    external: true
